apiVersion: v1
kind: Pod
metadata:
  generateName: test-pod-
spec:
  restartPolicy: OnFailure
  containers:
  - name: "executor"
    image: doittemp.azurecr.io/executor-test
    command: ['python3', 'executor.py', '{"atom_id": "string", "status": "queued", "requirements": {"cpu": 250, "mem": 64}, "name": "user_atom.MyAtom", "priority": 123}']
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
  imagePullSecrets:
  - name: regcred
        