apiVersion: v1
kind: Pod
metadata:
  generateName: test-pod-
spec:
  restartPolicy: OnFailure
  containers:
  - name: "executor"
    image: doittemp.azurecr.io/executor-image
    command: ['python3', 'executor.py', 'b{"atom_id": "123-250-64-user_atom.MyAtom", "status": "queued", "requirements": {"cpu": 250, "mem": 64}, "name": "user_atom.MyAtom", "priority": 123}']
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
  imagePullSecrets:
  - name: regcred
        